<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KTEDRBL" ignored="0" name="TC004_Login_Test_with_log4j2" tests="1" failures="1" timestamp="12 Jul 2023 17:50:43 GMT" time="13.232" errors="0">
  <testcase name="loginTest" time="8.029" classname="com.Facebook.testCases.TC004_Login_Test_with_log4j2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.Facebook.testCases.TC004_Login_Test_with_log4j2.loginTest(TC004_Login_Test_with_log4j2.java:50)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- TC004_Login_Test_with_log4j2 -->
